version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: your_app_name
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production
      - PORT=8001
      - DATABASE_URL=postgresql://postgres:postgres_password@postgres:5432/your_app_name
      - SECRET_KEY=cf235e9094c78b74ce6d7a95243eb05e13a79717ebb021fe80f5d28961807af372d2fee9e4fd248596e8475dc7ac322044c1ec0d438c102025152609e7210dc1
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: